### ISSUE TITLE
Blank results in simple example

### ISSUE THREAD

**Issue by po5i** [Automattic/es-backbone#2]
Hello, nice application. I am trying the example, it seems everythings ok but the results are empty blocks. I mean, the application do bring the results (the count and the facets its all right) but there is some kind of problem with the results template, I suppose in this part

```
        {{#hits}}\
        <p class="esbb-result"> \
            <span class="esbb-result-title">{{fields.title}}<span>\
            {{highlight.content}}<br \>\
            <span class="esbb-result-name">{{fields.authors}}</span>\
            - <span class="esbb-result-date">{{fields.location}}</span>\
        </p>\
        {{/hits}}\
```

the fields title, authors and location (in my case) are rendered as empty strings.

**Comment by po5i** [comment]
Figure it out: it's: {{_source.title}} etc.

**Comment by gibrown** [comment]
That part will depend a lot on what your index looks like. The example assumes that your index has fields defined for title, content, authors, and location. You probably need to change those to match whatever your index is. So in the example you can override the results field by modifying the templateResults that are passed in here: https://github.com/Automattic/es-backbone/blob/master/examples/simple/simple-view.js#L28

FYI, I have some pretty major updates to this lib I haven't committed because I haven't had time to update the example code. I'll try and get them up in the next week.

**Comment by gibrown** [comment]
:)

**Comment by po5i** [comment]
That's great to hear, I will be waiting for it.

Just to clarify, my field was _source specifically because I am using elasticsearch index with the couch-db river plugin (to perform fulltext search in couchdb).

Thanks for the reply

**Comment by po5i** [comment]
It would be really helpful if you could commit the updates soon, we are developing an opensource project for EU, and this will be the main component for the faceted search tool. I have to develop an application in order to generate and customize the search tool, maybe this can be interesting for you too.

Thanks again

**Comment by gibrown** [comment]
@po5i sorry about the delay. Updating (and testing) the sample application was holding me up, but no reason to prevent me from updating the main es-backbone.js code. master is now up to date.

Here is a diff for my internal application that shows how I am using what has changed: https://gist.github.com/gibrown/5577521

Hopefully that helps with your integration, let me know if you run into problems.

**Comment by po5i** [comment]
Maybe if you could send me your internal app files or guide me how to apply this patch? 

Thanks
