### ISSUE TITLE
Pagination for results

### ISSUE THREAD

**Issue by po5i** [Automattic/es-backbone#6]
I want to implement the pagination feature between results. I know that in the JSON query it must have the `from : 0,` line but, how it can be modified on runtime?

**Comment by gibrown** [comment]
Pagination would be awesome to have. 

I think the changes needed are:
- In esbbSearchQueryModel add functions to setFrom(), setSize() (pretty much identical to setSort())
- Create a new view esbbPaginationView showing the number of pages and links to the pages. The esbbSortView is probably the easiest existing view to model it on.
- Ideally should also update esbbSearchQueryModel.getURLQueryString() so that it adds from and size to the query string.

Thanks!

**Comment by po5i** [comment]
Thank you for the guidelines, 

I successfully made navigation links instead of pagination. Something like Previous & Next links. I named it esbbNavigationView.

Also all the places where model.search is called, I invoked t.model.setFrom(0) to reset the navigation.

Now I have to wrap the example finder to a good-looking interface powered by some js library.
